### ISSUE TITLE
import transformers

### ISSUE THREAD

**Issue by Saumya1915** [kamalojasv181/Hostility-Detection-in-Hindi-Posts#1]
whenever I'm writing import transformers I'm getting a error. Kindly help me with this

**Comment by kamalojasv181** [comment]
Post the error, please. Also, which version of transformer are you using?

**Comment by Saumya1915** [comment]
I'm using google colab. 
ModuleNotFoundError: No module named 'transformers'

**Comment by kamalojasv181** [comment]
That's because transformer module was installed on my local machine but is not installed by default on colab servers. Hence add a `!pip install transformers==3.5.1` command at the beginning

**Comment by kamalojasv181** [comment]
![image](https://user-images.githubusercontent.com/43926001/112132141-49b5df80-8bf0-11eb-8bb5-d568a9e99cce.png)
It should install the module

Do the same with other modules giving the error. Make sure that you specify the versions given in the readme

**Comment by Saumya1915** [comment]
![image](https://user-images.githubusercontent.com/43070615/112132301-7538ca00-8bf0-11eb-948f-2672ee106562.png)
still it is showing some error

**Comment by kamalojasv181** [comment]
Paste the complete code snippet

**Comment by Saumya1915** [comment]
from sklearn import preprocessing
import pandas as pd
import numpy as np
import torch
import random
from sklearn import metrics
import transformers
import re
import emoji
import os
from torch import cuda
from sklearn.model_selection import train_test_split

This is after installing transformers

**Comment by kamalojasv181** [comment]
Where is that line where u install?

**Comment by kamalojasv181** [comment]
Please post a complete ss. Also please paste code `like this`

**Comment by Saumya1915** [comment]
!pip install transformers==3.5.1
from data_processing import preprocessing
import pandas as pd
import numpy as np
import torch
import random
from sklearn import metrics
import transformers
import re
import emoji
import os
from torch import cuda
from sklearn.model_selection import train_test_split

**Comment by Saumya1915** [comment]
![image](https://user-images.githubusercontent.com/43070615/112135256-9a7b0780-8bf3-11eb-89ae-677a925171d7.png)
![image](https://user-images.githubusercontent.com/43070615/112135305-a6ff6000-8bf3-11eb-9862-b6659ddccefe.png)
![image](https://user-images.githubusercontent.com/43070615/112135339-aebf0480-8bf3-11eb-8701-e4f95b583445.png)

**Comment by kamalojasv181** [comment]
@AdarshKumar712 
https://github.com/huggingface/transformers/issues/8232

**Comment by kamalojasv181** [comment]
@Saumya1915 there are compatibility issues with transformer 3.5.1 and torch 1.8(version installed by default in colab). Do a `!pip install torch==1.5.0` in the beginning. I can verify that this works. We will definitely try to move the code to the current libraries. For now just use the versions mentioned.

**Comment by Saumya1915** [comment]
Thank you for the fix!
