### ISSUE TITLE
cd "./../../../"

### ISSUE THREAD

**Issue by Saumya1915** [kamalojasv181/Hostility-Detection-in-Hindi-Posts#2]
I'm getting invalid syntax in cd "./../../../". Kindly tell me what is the mistake here?
![image](https://user-images.githubusercontent.com/43070615/112163780-57c92780-8c13-11eb-9c4e-67c81efbb63b.png)

**Comment by mozhgan-momtaz** [comment]
I have the same issue.Could u find the solution to it?

**Comment by kamalojasv181** [comment]
Actually, the directory structure at the time of working must have been something else. So just delete this line. In case, wherever you find some file not found, just update the path. Make a PR if you can, I will merge it.

**Comment by mozhgan-momtaz** [comment]
Thank you for the answer. I try to pre-trained it by binary-classifier and indic-bert it gave me this error, I was wondering if you had this too:
"RuntimeError: The size of tensor a (200) must match the size of tensor b (128) at non-singleton dimension 1"
Thanks

**Comment by kamalojasv181** [comment]
I am really sorry. I have been busy these days. Can you please specify which file gives you this error?

**Comment by mozhgan-momtaz** [comment]
I understand that. It was on binary-classification py file. I could figure it out. (I need to use this comment : 
        config = AutoConfig.from_pretrained('ai4bharat/indic-bert')
        self.l1 = AutoModel.from_config(config=config)
instead of self.l1 = AutoModel.from_pretrained(model_path)

**Comment by kamalojasv181** [comment]
Yes. Thanks for pointing that out
