### ISSUE TITLE
 "RuntimeError: The size of tensor a (200) must match the size of tensor b (128) at non-singleton dimension 1" 

### ISSUE THREAD

**Issue by mozhgan-momtaz** [kamalojasv181/Hostility-Detection-in-Hindi-Posts#3]
Dear Kamal,
 try to pre-trained by binary-classifier and indic-bert it gave me this error, I was wondering if you had resolve the issue.

Thanks

**Comment by kamalojasv181** [comment]
@mozhgan-momtaz please tell me which file gives you this error?

**Comment by kamalojasv181** [comment]
@mozhgan-momtaz is this still an issue?

**Comment by mozhgan-momtaz** [comment]
No you can close it
