### ISSUE TITLE
main_multitast-learning.py

### ISSUE THREAD

**Issue by mozhgan-momtaz** [kamalojasv181/Hostility-Detection-in-Hindi-Posts#5]
Dear Kamal,
I am now working on multilabel classification on pretrained indic-bert model.However, unlike main_bin_classification.py, this file does not have any comment to train the multitask_learning.py .I was wondering if u put the comment here. I use this comments:

from data_processing import preprocessing
from multitask_learning import CustomDataset, ModelClass, multitask_classifier

data = preprocessing('./Dataset/constraint_Hindi_Train.csv')
arr = data.processed()

mod = multitask_classifier(arr,'ai4bharat/indic-bert', 'non-hostile',10, 1e-5)
mod.train_model()

**Comment by kamalojasv181** [comment]
Yes, I see. You need to use 
```
mod = multitask_classifier(arr,'ai4bharat/indic-bert', 'non-hostile',10, 1e-5)
mod.train_model()
```

Thanks for mentioning it. I can why someone using this code can get confused. I will edit this repo today and make it very usable. Thanks for pointing this out

**Comment by mozhgan-momtaz** [comment]
Sure, Thanks for sharing your work
