### ISSUE TITLE
Single Model Multi-Label Classification 

### ISSUE THREAD

**Issue by mozhgan-momtaz** [kamalojasv181/Hostility-Detection-in-Hindi-Posts#6]
Dear author,
I was wondering to see how I can do this task. I am asking this since I could not find any py file with this name.
Appreciate it

**Comment by kamalojasv181** [comment]
Use generate_csv.py . Although the code is not very good. If you can manage with it right now, go for it. If not, wait for it. We will improve it within 1-2 days.

**Comment by mozhgan-momtaz** [comment]
great look forward to it
